name: Build binaries and create GitHub release

# Set the permissions of the github token to the minimum and only enable what is needed
# See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions
permissions: {}

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    permissions:
      contents: write # for publishing release
    strategy:
      matrix:
        build:
          - os: ubuntu-24.04
          - os: ubuntu-24.04-arm

    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: cachix/install-nix-action@v31

      - run: nix develop --command make -j syshud

      - run: make -j syshud
