name: Build binaries and create GitHub release

# Set the permissions of the github token to the minimum and only enable what is needed
# See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions
permissions: {}

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    permissions:
      contents: write # for publishing release
    strategy:
      matrix:
        build:
          - os: ubuntu-24.04
          - os: ubuntu-24.04-arm

    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - run: docker build . -t syshud

      - run: docker run --rm -it -u $(id -u):$(id -g) -v .:/workspace syshud make -j
